"""Hub village props: build play/img/v2/sprites-hub.webp (packed atlas) + play/js/sprite-atlas-hub.js (ATLAS_HUB_RECTS).

Twelve furniture/props for the redesigned hub (rescued NPCs get their own rooms). All "generated, Milan style" (openai-image-gen
skill, gpt-image-2, quality medium, edit with a contact sheet of Milan's sprites as reference) in octomancer-web/art-src/hub/*.png,
on flat magenta (#FF00FF), keyed and despilled with key_magenta (same as r4), cropped by box and resized to the target heights.
Run from the repo root:
    python octomancer-web/tools/export_hub_art.py
"""
import json, os
import numpy as np
from PIL import Image

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', '..'))
SRC = os.path.join(ROOT, 'octomancer-web', 'art-src', 'hub')
PLAY = os.path.join(ROOT, 'site', 'octomancer', 'play')


def key_magenta(path):
    """A generated sheet on flat magenta -> RGBA with the key removed, the soft rim darkened (no light halo), despilled."""
    im = np.asarray(Image.open(path).convert('RGB')).astype(np.float32)
    R, G, B = im[..., 0], im[..., 1], im[..., 2]
    m = np.minimum(R, B) - G
    alpha = 1 - np.clip((m - 70.0) / 130.0, 0, 1)
    spill = np.clip((m - 20) / 180, 0, 1)
    out = im.copy()
    cap = G + 20
    out[..., 0] = np.where(spill > 0, np.minimum(R, cap + (R - cap) * (1 - spill)), R)
    out[..., 2] = np.where(spill > 0, np.minimum(B, cap + (B - cap) * (1 - spill)), B)
    edge = (alpha > 0.02) & (alpha < 0.98)
    out[edge] = out[edge] * 0.55
    return np.dstack([np.clip(out, 0, 255), alpha * 255]).astype(np.uint8)


def crop(rgba, box, thr=8):
    img = Image.fromarray(rgba[box[1]:box[3], box[0]:box[2]], 'RGBA')
    a = img.getchannel('A').point(lambda v: 255 if v > thr else 0)
    return img.crop(a.getbbox())


def fit(img, w=None, h=None):
    k = (w / img.width) if w else (h / img.height)
    return img.resize((max(1, round(img.width * k)), max(1, round(img.height * k))), Image.LANCZOS)


# sheet file -> [(name, box in the 1536 x 1024 sheet, target height)]
SHEETS = {
    'gen01-a.webp': [('divingBell', (100, 0, 640, 520), 200), ('workbench', (720, 100, 1480, 480), 150),
                    ('shellHouse', (90, 540, 640, 980), 220), ('kelpNest', (780, 580, 1440, 960), 100)],
    'gen02-b.webp': [('relicShelf', (90, 100, 850, 440), 130), ('practiceTarget', (900, 0, 1300, 540), 180),
                    ('arenaPillar', (280, 500, 600, 980), 200), ('wardrobe', (860, 555, 1280, 1010), 200)],
    'gen03-c.webp': [('spongeChair', (180, 20, 660, 540), 130), ('rubblePile', (730, 60, 1400, 520), 120),
                    ('tablet', (260, 580, 600, 980), 100), ('hangingLamp', (900, 500, 1180, 1000), 120)],
}
S = {}
for fn, items in SHEETS.items():
    g = key_magenta(os.path.join(SRC, fn))
    for name, box, h in items:
        S[name] = fit(crop(g, box), h=h)
# pull any leftover pink (red and blue both well above green) back to green
for name in S:
    a = np.asarray(S[name]).astype(np.float32)
    bad = (a[..., 0] > a[..., 1] + 25) & (a[..., 2] > a[..., 1] + 25) & (a[..., 3] > 0) & (a[..., 1] < 90)
    a[..., 0] = np.where(bad, a[..., 1] + 10, a[..., 0]); a[..., 2] = np.where(bad, a[..., 1] + 10, a[..., 2])
    S[name] = Image.fromarray(a.astype(np.uint8), 'RGBA')

order = sorted(S, key=lambda n: -S[n].height)
W, PAD = 768, 2
x = y = row_h = 0
rects = {}
for n in order:
    im = S[n]
    if x + im.width + PAD > W:
        x, y, row_h = 0, y + row_h + PAD, 0
    rects[n] = [x, y, im.width, im.height]
    x += im.width + PAD
    row_h = max(row_h, im.height)
H = y + row_h
sheet = Image.new('RGBA', (W, H), (0, 0, 0, 0))
for n, (rx, ry, rw, rh) in rects.items():
    sheet.alpha_composite(S[n], (rx, ry))
out = os.path.join(PLAY, 'img', 'v2', 'sprites-hub.webp')
sheet.save(out, quality=90, method=6, alpha_quality=90)
with open(os.path.join(PLAY, 'js', 'sprite-atlas-hub.js'), 'w', encoding='utf-8', newline='\n') as f:
    f.write('// Generated by octomancer-web/tools/export_hub_art.py: the rects [x, y, w, h] of img/v2/sprites-hub.webp. Do not edit.\n')
    f.write('export const ATLAS_HUB_RECTS = {\n' + ''.join('  %s: %s,\n' % (json.dumps(k), json.dumps(v, separators=(',', ':'))) for k, v in rects.items()) + '};\n')
print('sheet', W, H, os.path.getsize(out), 'bytes')
for n in order: print(n, rects[n])
