"""Round 4 art pass (spells): build play/img/v2/sprites-r4.webp (packed atlas) + play/js/sprite-atlas-r4.js (rects), and
play/img/v2/mat-coral.webp (a seamless 512 px coral wall texture).

Sprites: four hotbar spell icons (iconRiptide, iconCoralWall, iconAnchor, iconLure, 128 px tall like iconInkCloud) and three
rune stones (runeHeavy, runeDelayed, runeLingering, 96 px tall). All "generated, Milan style" (openai-image-gen skill,
gpt-image-2, quality medium, edit with a contact sheet of Milan's sprites + the round 3 icon sheet as references) in
octomancer-web/art-src/r4/*.webp; sprites sit on flat magenta (#FF00FF), keyed and despilled with key_magenta (same as r3).
The coral texture was generated edge to edge; it is made to tile here by blending it with a half-size wrapped copy
(the seams then sit in the middle of the copy, where the picture is continuous) and resized to 512 px.
Run from the repo root:
    python octomancer-web/tools/export_r4_art.py
"""
import json, os
import numpy as np
from PIL import Image

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', '..'))
SRC = os.path.join(ROOT, 'octomancer-web', 'art-src', 'r4')
PLAY = os.path.join(ROOT, 'site', 'octomancer', 'play')


def key_magenta(path):
    """A generated sheet on flat magenta -> RGBA with the key removed, the soft rim darkened (no light halo), despilled."""
    im = np.asarray(Image.open(path).convert('RGB')).astype(np.float32)
    R, G, B = im[..., 0], im[..., 1], im[..., 2]
    m = np.minimum(R, B) - G
    alpha = 1 - np.clip((m - 70.0) / 130.0, 0, 1)
    spill = np.clip((m - 20) / 180, 0, 1)
    out = im.copy()
    cap = G + 20
    out[..., 0] = np.where(spill > 0, np.minimum(R, cap + (R - cap) * (1 - spill)), R)
    out[..., 2] = np.where(spill > 0, np.minimum(B, cap + (B - cap) * (1 - spill)), B)
    edge = (alpha > 0.02) & (alpha < 0.98)
    out[edge] = out[edge] * 0.55
    return np.dstack([np.clip(out, 0, 255), alpha * 255]).astype(np.uint8)


def crop(rgba, box, thr=8):
    img = Image.fromarray(rgba[box[1]:box[3], box[0]:box[2]], 'RGBA')
    a = img.getchannel('A').point(lambda v: 255 if v > thr else 0)
    return img.crop(a.getbbox())


def fit(img, w=None, h=None):
    k = (w / img.width) if w else (h / img.height)
    return img.resize((max(1, round(img.width * k)), max(1, round(img.height * k))), Image.LANCZOS)


S = {}
g1 = key_magenta(os.path.join(SRC, 'gen01-icons.webp'))
for name, box in [('iconRiptide', (240, 50, 680, 480)), ('iconCoralWall', (880, 40, 1240, 480)),
                  ('iconAnchor', (240, 500, 650, 970)), ('iconLure', (860, 530, 1240, 950))]:
    S[name] = fit(crop(g1, box), h=128)
# the riptide's feathered tip carries a pinkish blend of the key: pull any pixel with both red and blue above green back to its green
for name in S:
    a = np.asarray(S[name]).astype(np.float32)
    bad = (a[..., 0] > a[..., 1] + 25) & (a[..., 2] > a[..., 1] + 25)
    a[..., 0] = np.where(bad, a[..., 1] + 10, a[..., 0]); a[..., 2] = np.where(bad, a[..., 1] + 10, a[..., 2])
    S[name] = Image.fromarray(a.astype(np.uint8), 'RGBA')
g2 = key_magenta(os.path.join(SRC, 'gen02-runes.webp'))
for name, box in [('runeHeavy', (120, 280, 530, 730)), ('runeDelayed', (570, 280, 960, 730)), ('runeLingering', (1030, 280, 1410, 730))]:
    S[name] = fit(crop(g2, box), h=96)

order = sorted(S, key=lambda n: -S[n].height)
W, PAD = 512, 2
x = y = row_h = 0
rects = {}
for n in order:
    im = S[n]
    if x + im.width + PAD > W:
        x, y, row_h = 0, y + row_h + PAD, 0
    rects[n] = [x, y, im.width, im.height]
    x += im.width + PAD
    row_h = max(row_h, im.height)
H = y + row_h
sheet = Image.new('RGBA', (W, H), (0, 0, 0, 0))
for n, (rx, ry, rw, rh) in rects.items():
    sheet.alpha_composite(S[n], (rx, ry))
out = os.path.join(PLAY, 'img', 'v2', 'sprites-r4.webp')
sheet.save(out, quality=88, method=6, alpha_quality=90)
with open(os.path.join(PLAY, 'js', 'sprite-atlas-r4.js'), 'w', encoding='utf-8', newline='\n') as f:
    f.write('// Generated by octomancer-web/tools/export_r4_art.py: the rects [x, y, w, h] of img/v2/sprites-r4.webp. Do not edit.\n')
    f.write('export const ATLAS_R4_RECTS = {\n' + ''.join('  %s: %s,\n' % (json.dumps(k), json.dumps(v, separators=(',', ':'))) for k, v in rects.items()) + '};\n')
print('sheet', W, H, os.path.getsize(out), 'bytes')
for n in order: print(n, rects[n])

# ---------------------------------------------------------------- coral texture: make it tile, 512 px
tex = np.asarray(Image.open(os.path.join(SRC, 'gen03-coral.webp')).convert('RGB')).astype(np.float32)
n = tex.shape[0]
rolled = np.roll(np.roll(tex, n // 2, 0), n // 2, 1)
u = np.abs(np.arange(n) + 0.5 - n / 2) / (n / 2)           # 0 at the middle, 1 at the edges
ramp = lambda d: np.clip((0.85 - d) / 0.35, 0, 1)            # 1 inside, falls to 0 towards the edge
ramp = lambda d: (lambda t: t * t * (3 - 2 * t))(np.clip((0.9 - d) / 0.4, 0, 1))
w = (ramp(u)[:, None] * ramp(u)[None, :])[..., None]
tile = tex * w + rolled * (1 - w)
img = Image.fromarray(np.clip(tile, 0, 255).astype(np.uint8)).resize((512, 512), Image.LANCZOS)
cout = os.path.join(PLAY, 'img', 'v2', 'mat-coral.webp')
img.save(cout, quality=86, method=6)
print('mat-coral', os.path.getsize(cout), 'bytes')
