"""Octopus skins (2026-10-08): build play/img/v2/skins.webp (packed atlas) + play/js/skin-atlas.js (rects).

Sprites: three skin accessories (goggles = Marlo's sea-glass diving goggles, worn pushed up on the forehead; monocle = Quill's;
tophat = the pool host's kelp top hat) and the hub's mirror shell (the wardrobe you swim to and press F). Generated, Milan style
(openai-image-gen skill, gpt-image-2, quality medium, edit with a contact sheet of Milan's sprites as the reference: octopus idle
frame, shell-blue, urchin, crab, snail, jelly, the sea-glass goggles item) in octomancer-web/art-src/skins/*.webp on flat
magenta (#FF00FF), keyed and despilled the same way as the r4 art (export_r4_art.py key_magenta).
Run from the repo root:
    python octomancer-web/tools/export_skins_art.py
"""
import os
import numpy as np
from PIL import Image

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', '..'))
SRC = os.path.join(ROOT, 'octomancer-web', 'art-src', 'skins')
PLAY = os.path.join(ROOT, 'site', 'octomancer', 'play')


def key_magenta(path):
    im = np.asarray(Image.open(path).convert('RGB')).astype(np.float32)
    R, G, B = im[..., 0], im[..., 1], im[..., 2]
    m = np.minimum(R, B) - G
    alpha = 1 - np.clip((m - 70.0) / 130.0, 0, 1)
    spill = np.clip((m - 20) / 180, 0, 1)
    out = im.copy()
    cap = G + 20
    out[..., 0] = np.where(spill > 0, np.minimum(R, cap + (R - cap) * (1 - spill)), R)
    out[..., 2] = np.where(spill > 0, np.minimum(B, cap + (B - cap) * (1 - spill)), B)
    edge = (alpha > 0.02) & (alpha < 0.98)
    out[edge] = out[edge] * 0.55
    return np.dstack([np.clip(out, 0, 255), alpha * 255]).astype(np.uint8)


def crop(rgba, box, thr=8):
    img = Image.fromarray(rgba[box[1]:box[3], box[0]:box[2]], 'RGBA')
    a = img.getchannel('A').point(lambda v: 255 if v > thr else 0)
    return img.crop(a.getbbox())


def fit(img, w=None, h=None):
    k = (w / img.width) if w else (h / img.height)
    return img.resize((max(1, round(img.width * k)), max(1, round(img.height * k))), Image.LANCZOS)


S = {}
g1 = key_magenta(os.path.join(SRC, 'gen01-accessories.webp'))
S['accGoggles'] = fit(crop(g1, (0, 300, 600, 650)), w=160)
S['accMonocle'] = fit(crop(g1, (620, 300, 960, 760)), h=128)
S['accTophat'] = fit(crop(g1, (1020, 300, 1536, 700)), w=144)
g2 = key_magenta(os.path.join(SRC, 'gen02-mirror.webp'))
S['mirrorShell'] = fit(crop(g2, (0, 0, 1024, 1024)), h=256)

# pack in one row (small atlas)
pad = 4
W = sum(im.width + pad for im in S.values()) + pad
H = max(im.height for im in S.values()) + pad * 2
atlas = Image.new('RGBA', (W, H), (0, 0, 0, 0))
rects = {}
x = pad
for name, im in S.items():
    atlas.paste(im, (x, pad))
    rects[name] = (x, pad, im.width, im.height)
    x += im.width + pad
out = os.path.join(PLAY, 'img', 'v2', 'skins.webp')
atlas.save(out, 'WEBP', quality=90, method=6)
lines = ['// Generated by octomancer-web/tools/export_skins_art.py: rects in img/v2/skins.webp [x, y, w, h].',
         'export const SKIN_ATLAS = {']
for k, (a, b, c, d) in rects.items():
    lines.append(f'  {k}: [{a}, {b}, {c}, {d}],')
lines.append('};')
with open(os.path.join(PLAY, 'js', 'skin-atlas.js'), 'w', newline='\n') as f:
    f.write('\n'.join(lines) + '\n')
print(out, atlas.size, rects)
