#!/usr/bin/env python3
"""Round 42: Milan Svancara's Whirlpool sprite animation (octomancer-unity, read-only) -> one webp sheet.

Frame order and fps come from the .anim files (the guids of the sprite keys, mapped through the .png.meta files):
  Whirlpool1.anim        idle loop    5 frames, 12 fps (WhirlpoolAnimation1..5), loops
  Whirlpool1Bounce.anim  bounce      10 frames, 12 fps (WhirlpoolBounce1..10), loops (played once when the octopus enters)
  Whirlpool1Rise.anim    rise         6 frames, 12 fps (WhirlpoolRise0..5), no loop
All sprites share one scale (100 px per unit) and a centre pivot, so each frame is pasted centred in a square cell.
SCALE 0.30: the idle whirlpool (557 px wide in the source) becomes ~167 px = 2.3 tiles at 72 px tiles.
Offline tool only. Run from the repo root:  python octomancer-web/tools/export_whirlpool.py
"""
import re
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "octomancer-unity" / "Assets" / "Sprites" / "Elements (Bubbles, flames...)" / "Whirlpool"
DST_DIR = ROOT / "site" / "octomancer" / "play" / "img" / "v2"
COLS = 7
# r44: two sheets from the same frames. The normal one (SCALE 0.30, 208 px cells, idle 167 px) serves every screen up to a 1x/1.5x phone
# or desktop; the 'hi' one (SCALE 0.55, 380 px cells, idle 306 px) is used only when the device pixel ratio is 2 or more AND the viewport
# is wider than 900 css px (a DPR 2 desktop drew the 0.30 sheet 1.9x too big and it looked soft). Each file stays under 300 KB.
SHEETS = [
    # key, file, scale, cell, webp quality, webp alpha quality (the soft alpha edges of the big sheet are what costs bytes)
    ("lo", "whirlpool-sheet.webp", 0.30, 208, 80, 100),
    ("hi", "whirlpool-sheet-hi.webp", 0.55, 380, 70, 40),
]
META = ROOT / "site" / "octomancer" / "play" / "js" / "whirlpool-meta.js"
ALPHA_SEEN = 40  # a pixel counts as visible from this alpha (0-255); the faint glow below it does not seat the frame


def guid_map():
    m = {}
    for meta in SRC.glob("*.png.meta"):
        g = re.search(r"^guid: (\w+)", meta.read_text(), re.M).group(1)
        m[g] = meta.name[:-9]
    return m


def frames(anim, g2n):
    txt = (SRC / anim).read_text()
    block = txt.split("m_PPtrCurves:")[1].split("m_SampleRate")[0]
    return [g2n[g] for g in re.findall(r"time: [\d.]+\n\s+value: \{fileID: \d+, guid: (\w+)", block)]


def main():
    g2n = guid_map()
    seqs = [("idle", "Whirlpool1.anim"), ("bounce", "Whirlpool1Bounce.anim"), ("rise", "Whirlpool1Rise.anim")]
    names = []
    for key, a in seqs:
        f = frames(a, g2n)
        print(key, f)
        names += f
    rows = (len(names) + COLS - 1) // COLS
    meta = {}
    for key, fname, scale, cell, q, aq in SHEETS:
        sheet = Image.new("RGBA", (COLS * cell, rows * cell), (0, 0, 0, 0))
        bottoms, tops, lefts, rights, widths = [], [], [], [], []
        for i, n in enumerate(names):
            im = Image.open(SRC / (n + ".png")).convert("RGBA")
            im = im.resize((round(im.width * scale), round(im.height * scale)), Image.LANCZOS)
            cx, cy = (i % COLS) * cell + cell // 2, (i // COLS) * cell + cell // 2
            sheet.alpha_composite(im, (cx - im.width // 2, cy - im.height // 2))
            widths.append(im.width)
            # the visible box of this frame inside its own cell: the Bounce frames lift 0.4 tile and the idle ones hover because the
            # sprites are not drawn on a common baseline, so the game seats each frame by its own visible bottom (r44)
            a = im.getchannel("A").point(lambda v: 255 if v >= ALPHA_SEEN else 0)
            bb = a.getbbox()
            ox, oy = cell // 2 - im.width // 2, cell // 2 - im.height // 2
            lefts.append(bb[0] + ox); tops.append(bb[1] + oy); rights.append(bb[2] + ox); bottoms.append(bb[3] + oy)
        dst = DST_DIR / fname
        sheet.save(dst, "WEBP", quality=q, alpha_quality=aq, method=6)
        print(key, dst, sheet.size, dst.stat().st_size, "bytes")
        meta[key] = dict(file=fname, cell=cell, cols=COLS, idlePx=round(sum(rights[i] - lefts[i] for i in range(5)) / 5), bottoms=bottoms, tops=tops)
    # the idle frames' mean visible width is the unit the game scales by (the idle whirlpool is PORTAL_TILES wide)
    lines = ["// Generated by octomancer-web/tools/export_whirlpool.py (r44). Do not edit.",
             "// Per sheet: cell size, the idle whirlpool's visible width (px), and each of the 21 frames' visible top / bottom (px, inside its cell).",
             "export const WHIRL_SHEETS = {"]
    for key, m in meta.items():
        lines.append(f"  {key}: {{ file: '{m['file']}', cell: {m['cell']}, cols: {m['cols']}, idlePx: {m['idlePx']}, bottoms: {m['bottoms']}, tops: {m['tops']} }},")
    lines.append("};")
    META.write_text(chr(10).join(lines) + chr(10), encoding="utf8")
    print(META)


if __name__ == "__main__":
    main()
